### ISSUE TITLE
Return if child process is nil: Is this correct?

### ISSUE THREAD

**Issue by ClaytonNorthey92** [cedana/cedana#100]
Hi all, I noticed [this line of code](https://github.com/cedana/cedana/blob/f50b2dae760b4e19322cc03ca31d0ea0e37e1f6a/cmd/client-daemon.go#L58):
```go
d, err := ctx.Reborn()
if err != nil {
	logger.Err(err).Msg("could not start daemon")
}

if d != nil { // <-- here
	return
}
```

is this just returning if the "child process" created from `ctx.Reborn` is _not_ null? meaning, if it was created, return and exit? is this right? 🤔 

also, it seems that `go-daemon` isn't actively maintained, the last merge was in March at the time of writing this.  may I ask why it was chosen?

**Comment by morka17** [comment]
Yeah, `go-daemon` might be well-suited for the intended deployment environments and configurations.

Also try exploring actively maintained alternatives like:
- sevki/go-daemon: https://github.com/takama/daemon
- kardianos/service: https://github.com/kardianos/service
