### ISSUE TITLE
Registration URL returns error

### ISSUE THREAD

**Issue by simaattar2003** [cedana/cedana#337]
Good day!

The registration URL https://auth.cedana.com/ui/registration returns error:
```
{
  "error": {
    "code": 404,
    "message": "No resource found using the specified path.",
    "reason": "Invalid path",
    "status": "Not Found"
  }
}
```

**Comment by nravic** [comment]
Hi Sima, we changed the registration endpoint recently, so just take a look at auth.cedana.com. 

Closing this.
